services:
  - type: web
    name: myluckyroulette-app
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CRAWLER_SOURCE
        value: casinoorg
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
